import React, { useEffect, useState } from "react";
import AppLayout from "../components/AppLayout";
import Loader from "../components/Loader";
import API from "../services/api";
import { Link } from "react-router-dom";

const AdminDashboardPage: React.FC = () => {
  const [welcomeMsg, setWelcomeMsg] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const verifyAdmin = async () => {
      try {
        setLoading(true);
        const res = await API.get<{ message: string }>("/admin/dashboard");
        setWelcomeMsg(res.data.message || "Welcome Admin");
      } catch (err) {
        console.error("Admin verification failed:", err);
        setError("Unauthorized: Admin access verified failed.");
      } finally {
        setLoading(false);
      }
    };

    verifyAdmin();
  }, []);

  return (
    <AppLayout>
      <div className="container-fluid px-0">
        <div className="mb-4">
          <h1 className="h2 text-white mb-1">Admin Control Center</h1>
          <p className="text-light-gray">Manage SpotiMERN music assets and system settings.</p>
        </div>

        {loading ? (
          <Loader />
        ) : error ? (
          <div className="alert alert-danger" role="alert">
            <i className="bi bi-shield-lock-fill me-2"></i>
            {error}
          </div>
        ) : (
          <div className="row g-4 mt-2">
            <div className="col-12">
              <div className="spotify-card p-4 text-start mb-4">
                <h3 className="text-success mb-2">
                  <i className="bi bi-shield-check me-2"></i>
                  {welcomeMsg}
                </h3>
                <p className="text-light-gray mb-0">
                  You are authorized with administrative permissions. You can perform full CRUD catalog operations, toggle track visibility, and audit system notifications.
                </p>
              </div>
            </div>

            {/* Quick Administration Cards */}
            <div className="col-md-6">
              <div className="spotify-card text-start h-100 d-flex flex-column justify-content-between">
                <div>
                  <h4 className="text-white mb-2">
                    <i className="bi bi-music-note-list text-success me-2"></i>
                    Track Catalogue
                  </h4>
                  <p className="text-light-gray mb-4" style={{ fontSize: "0.85rem" }}>
                    Add new audio tracks, modify metadata (artist name, album, release date, durations), toggle public listing visibility, or permanently delete items.
                  </p>
                </div>
                <Link to="/admin/songs" className="btn btn-spotify w-100 py-2.5 mt-auto">
                  MANAGE MUSIC CATALOGUE
                </Link>
              </div>
            </div>

            <div className="col-md-6">
              <div className="spotify-card text-start h-100 d-flex flex-column justify-content-between">
                <div>
                  <h4 className="text-white mb-2">
                    <i className="bi bi-bell-fill text-success me-2"></i>
                    System Notifications
                  </h4>
                  <p className="text-light-gray mb-4" style={{ fontSize: "0.85rem" }}>
                    Audit notifications generated by catalogue edits. When you add a new song, users will receive a system alert in their notification feeds.
                  </p>
                </div>
                <Link to="/notifications" className="btn btn-spotify-outline w-100 py-2.5 mt-auto">
                  AUDIT NOTIFICATIONS
                </Link>
              </div>
            </div>
          </div>
        )}
      </div>
    </AppLayout>
  );
};

export default AdminDashboardPage;
